#!/bin/bash
# ------------------------------------------------------------------------------ -
# 
# Copyright © 2018 Koninklijke Philips N.V.
# 
# Authors : Bart Kroon
# Contact : bart.kroon@philips.com
# 
# SVS example script
# This script runs SVS with the supplied example configuration. It doubles up as a
# regression test by comparing the result with a reference.
# 
# 
# Permission is hereby granted, free of charge, to the members of the Moving Picture 
# Experts Group(MPEG) obtaining a copy of this software and associated documentation 
# files(the "Software"), to use the Software exclusively within the framework of the 
# MPEG - I(immersive) and MPEG - I Visual activities, for the sole purpose of 
# developing the MPEG - I standard. This permission explicitly excludes the rights
# to publish, distribute, sublicense, sell, embed into a product r a service and/or
# otherwise commercially exploit copies of the Software without the written consent
# of the owner (Koninklijke Philips N.V.).
# 
# This permission is provided subject to the following conditions :
# The above copyright notice and this permission notice shall be included in all 
# copies, substantial portions or derivative works of the Software.
# 
# ------------------------------------------------------------------------------ -

trap exit ERR

# Verify that the ULB_Unicorn archive is here
if [ ! -f "Plane_B'_Kinect.zip" ]
then
	echo "First download Plane_B'_Kinect.zip from the MPEG content server at /MPEG-I/ULB/ULB_Unicorn/PLANES/"
	# For example:
	#   ln -s /some/folder/VR/MPEG/ULB_Unicorn/Plane_B'_Kinect.zip .
	exit 1
fi

# Verify that the executable is here
if [ ! -f "SVS" ]
then
	echo "Build the project and make a symlink to the executable or copy it here"
	# For example:
	#   mkdir -p build/linux
	#   pushd build/linux
	#   cmake-gui ../..
	#   make
	#   popd
	#   ln -s build/linux/SVS/SVS .
	exit 1
fi

# Unzip if not already done
[ -f "Plane_B'/cams_unicorn_vsrs.txt" ] || unzip "Plane_B'_Kinect.zip"

# Reconstruct missing z_value_DERS.txt
if [ ! -f "z_value_DERS.txt" ]
then
	f="z_value_DERS.txt"
	for i in "Plane_B'/Plane_B'_Depth/"Kinect_*.yuv
	do
		echo $i 						>> $f
		echo NearestDepthValue 500.0	>> $f
		echo FarthestDepthValue 2000.0	>> $f
		echo 							>> $f
	done
fi

# Run
./SVS config_files/example_config_file.cfg

# Bit-true check
echo 681e96bb598cf47db89a2cbd3727b06a *055003250438_from_030003070370_030003430506.yuv | md5sum -c

