#!/bin/bash

# The copyright in this software is being made available under the BSD
# License, included below. This software may be subject to other third party
# and contributor rights, including patent rights, and no such rights are
# granted under this license.
#
# Copyright (c) 2010-2018, ITU/ISO/IEC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#  * Neither the name of the ITU/ISO/IEC nor the names of its contributors may
#    be used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.


# Original authors:
# 
# Universite Libre de Bruxelles, Brussels, Belgium:
# 	Sarah Fachada, Sarah.Fernandes.Pinto.Fachada@ulb.ac.be
# 	Daniele Bonatto, Daniele.Bonatto@ulb.ac.be
# 	Arnaud Schenkel, arnaud.schenkel@ulb.ac.be
# 
# Koninklijke Philips N.V., Eindhoven, The Netherlands:
# 	Bart Kroon, bart.kroon@philips.com
# 	Bart Sonneveldt, bart.sonneveldt@philips.com


trap exit ERR

function compute()
{
    for testcase in A1 A2 A3
    do
	    for view in {0..14}
	    do
		    original="ClassroomVideo/v${view}_4096_2048_420_10b.yuv"
		    reconstructed="$1/ClassroomVideo/${testcase}/${testcase}_v${view}_4096_2048_420_10b$2.yuv"
		    echo -n "$testcase $view "
		    wspsnr -w 4096 -h 2048 -n 1 -y 360 -p 180 -d 10 -o $original -r $reconstructed | tail -n 1
	    done
    done

    for testcase in B1 B2 B3
    do
	    for view in {0..23}
	    do
		    original="TechnicolorMuseum/v${view}_2048_2048_420_10b.yuv"
		    reconstructed="$1/TechnicolorMuseum/${testcase}/${testcase}_v${view}_2048_2048_420_10b$2.yuv"
		    echo -n "$testcase $view "
		    wspsnr -w 2048 -h 2048 -n 1 -y 180 -p 180 -d 10 -o $original -r $reconstructed | tail -n 1
	    done
    done

    for testcase in C1 C2 C3
    do
	    for view in {0..9}
	    do
		    original="TechnicolorHijack/v${view}_4096_4096_420_10b.yuv"
		    reconstructed="$1/TechnicolorHijack/${testcase}/${testcase}_v${view}_4096_4096_420_10b$2.yuv"
		    echo -n "$testcase $view "
		    wspsnr -w 4096 -h 4096 -n 1 -y 180 -p 180 -d 10 -o $original -r $reconstructed | tail -n 1
	    done
    done
} 

compute output | tee regular.wspsnr
compute masked_output _masked | tee masked.wspsnr

